[package]
name = "annunaki-service"
version = "0.1.0"
authors = ["Will Tokunaga <thrill.ssb@gmail.com>", "Izzy Swart <zenerboson@gmail.com>"]
edition = "2018"

[dependencies]
annunaki = { path = "../" }