[package]
name = "annunaki-web-server"
version = "0.1.0"
authors = ["Will Tokunaga <thrill.ssb@gmail.com>", "Izzy Swart <zenerboson@gmail.com>"]
edition = "2018"

[dependencies]
annunaki = { path = "../../" }
annunaki-web = { path = "../" }
askama = "0.8"